name: speedtest-tracker-nexus
services:
  speedtest-tracker:
    environment:
      PGID: $PGID
      PUID: $PUID
      DB_CONNECTION: sqlite
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    ports:
      - target: 80
        published: ${WEBUI_PORT:-80}
        protocol: tcp
    volumes:
      - /DATA/AppData/$AppID/config:/config

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: speedtest-tracker
  description:
    en_us: Speedtest Tracker is a self-hosted internet performance tracking application that runs speedtest checks against Ookla's Speedtest service.
  tagline:
    en_us: Speedtest Tracker
  developer: alexjustesen
  author: Nexus-Apps
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/MySpeed/icon.png
  thumbnail: ""
  title:
    en_us: Speedtest Tracker
  category: Nexus-Apps
  port_map: ${WEBUI_PORT:-80}
