name: adguard-home
services:
  app:
    container_name: adguard-home
    image: adguard/adguardhome:latest
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    ports:
      - target: 3000
        published: ${WEBUI_PORT:-3000}
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/work
        target: /opt/adguardhome/work
      - type: bind
        source: /DATA/AppData/$AppID/conf
        target: /opt/adguardhome/conf
    restart: unless-stopped
    network_mode: host
    privileged: false

x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: adguard
  category: Nexus-Store
  description:
    en_us: AdGuard Home is a network-wide software for blocking ads & tracking. After you set it up, it’ll cover ALL your home devices, and you don’t need any client-side software for that. 
  developer: adguard
  icon: https://cdn.jsdelivr.net/gh/nexusdiscord/Nexus-Apps@main/Apps/adguard-home/icon.png
  index: /
  main: app
  port_map: ${WEBUI_PORT:-3000}
  scheme: http
  tagline:
    en_us: AdGuard Home is a network-wide software for blocking ads & tracking. After you set it up, it’ll cover ALL your home devices, and you don’t need any client-side software for that. 
  store_app_id: adguard-home
  title:
    en_us: AdGuard Home
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/nexusdiscord/Nexus-Apps@main/Apps/adguard-home/screenshot-01.png
  thumbnail: https://cdn.jsdelivr.net/gh/nexusdiscord/Nexus-Apps@main/Apps/adguard-home/thumbnail.png