name: filebrowser-nexus
services:
  filebrowser:
    environment:
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    image: filebrowser/filebrowser:latest
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 80
        published: ${WEBUI_PORT:-80}
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/db
        target: /db
      - type: bind
        source: /DATA
        target: /srv
    container_name: filebrowser

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: filebrowser
  author: filebrowser
  category: Nexus-Apps
  description:
    en_us: File Browser - Webbased File Browser including sharing functions etc.
  developer: File Browser
  icon: https://cdn.jsdelivr.net/gh/nexusdiscord/Nexus-Apps@main/Apps/filebrowser/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/nexusdiscord/Nexus-Apps@main/Apps/filebrowser/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/nexusdiscord/Nexus-Apps@main/Apps/filebrowser/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/nexusdiscord/Nexus-Apps@main/Apps/filebrowser/screenshot-3.jpg
  tagline:
    en_us: Upload, delete, preview, rename, edit and share your files.
  thumbnail: https://cdn.jsdelivr.net/gh/nexusdiscord/Nexus-Apps@main/Apps/filebrowser/thumbnail.jpg
  tips:
    before_install:
      en_us: |
        Default Account

        | Username | Password |
        | -------- | -------- |
        | `admin`    | `admin`    |
  title:
    en_us: FileBrowser
  store_app_id: filebrowser-nexus
  index: /
  port_map: ${WEBUI_PORT:-80}
