name: metube-nexus
services:
  metube:
    environment:
      PGID: $PGID
      PUID: $PUID
    image: ghcr.io/alexta69/metube
    container_name: metube
    ports:
      - target: 8081
        published: ${WEBUI_PORT:-8081}
        protocol: tcp
    volumes:
      - /DATA:/downloads

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  main: metube
  description:
    en_us: Web GUI for youtube-dl (using the yt-dlp fork) with playlist support. Allows you to download videos from YouTube and dozens of other sites.
  tagline:
    en_us: MeTube
  developer: alexta69
  author: Nexus-Apps
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@main/png/metube.png
  thumbnail: ""
  title:
    en_us: MeTube
  category: Nexus-Apps
  port_map: ${WEBUI_PORT:-8081}
